.SH NAME
internsctl \- Utility to get system data and more
.SH DESCRIPTION
.B test.sh
This command uses multiple arguments to get system data and more
.SH OPTIONS
.TP
.BR help
gets help
.TP
.BR cpu getinfo
gets cpu info
.TP
.BR create USERNAME
creates user
.TP
.BR --sudo-only
gets user with sudo priviledges
.TP
.BR --last-modified
gets when was file last modified
.TP
.BR --owner
gets file owner
.TP
.BR --permissions
gets file permissins
.TP
.BR --size
gets file size
